### ISSUE TITLE
Add extensions methods EqualsIgnoreCase StartsWithIgnoreCase EndsWithIgnoreCase

### ISSUE THREAD

**Issue by gigi81** [soenneker/soenneker.extensions.string#288]
Hi,
I was wondering if you could add to this library the following extension methods to `string`

- EqualsIgnoreCase
- StartsWithIgnoreCase
- EndsWithIgnoreCase

I always find myself adding these methods to my code.

Example usage would be, instead of:
```
obj.Equals(value, StringComparison.InvariantCultureIgnoreCase);
```

Would become:
```
obj.EqualsIgnoreCase(value);
```

I hope you can appreciate how more concise and readable this is.
Let me know what you think.
Happy to have a PR for this if this is something you would eventually merge.
Thanks

**Comment by soenneker** [comment]
@gigi81 Thanks for the suggestion - implemented and deployed. I used ordinal instead of invariant culture... let me know if there are any issues with that

**Comment by gigi81** [comment]
@soenneker thanks for actioning this so quickly and yes you are absolutely correct, the ordinal is the more correct choice.

I have some other ideas for `IEnumerable<string>` extensions  will open other PR(s) for that.

oh, in case you want to use them, here are some unit tests I started writing...

```c#
  [Theory]
  //true cases
  [InlineData("test", "test", true)]
  [InlineData("Test", "test", true)]
  [InlineData("Test", "Test", true)]
  [InlineData("test", "TeSt", true)]
  [InlineData(".<test", ".<TeSt", true)]
  [InlineData(".<testè", ".<TeStÈ", true)]
  //false cases
  [InlineData("test", null, false)]
  [InlineData("test", "", false)]
  [InlineData("test1", "test2", false)]
  [InlineData("à-test", "è-test", false)]
  public void EqualsIgnoreCase_ShouldReturnExpectedResult(string str, string? value, bool expected)
  {
      // Act
      var result = str.EqualsIgnoreCase(value);
      
      // Assert
      result.Should().Be(expected);
  }
  
  [Theory]
  //true cases
  [InlineData("testABC", "", true)]
  [InlineData("testABC", "test", true)]
  [InlineData("TestABC", "test", true)]
  [InlineData("TestABC", "Test", true)]
  [InlineData("testABC", "TeSt", true)]
  [InlineData(".<testABC", ".<TeSt", true)]
  [InlineData(".<testèABC", ".<TeStÈ", true)]
  //false cases
  [InlineData("à-testABC", "è-test", false)]
  public void StartsWithIgnoreCase_ShouldReturnExpectedResult(string str, string value, bool expected)
  {
      // Act
      var result = str.StartsWithIgnoreCase(value);
      
      // Assert
      result.Should().Be(expected);
  }
```
